import { toClassName } from '../../scripts/aem.js';
import { getWistiaId } from '../../scripts/wistia.js';

/*
 * UI strings generated by the block. English is the default; add a locale
 * (keyed by <html lang>, set by scripts.js from the path) to translate, e.g.
 * STRINGS.fr = { filter: 'Filtrer', ... }. Missing keys fall back to English.
 * `{0}` is replaced by a value (count or filter name).
 */
const STRINGS = {
  en: {
    filter: 'Filter',
    openFilter: 'Filter',
    closeFilter: 'Close filter',
    seeResults: 'See Results',
    category: 'Category',
    productType: 'Product Type',
    product: '{0} product',
    products: '{0} products',
    showing: 'Showing {0}',
    removeFilter: 'Remove {0} filter',
    removeAll: 'Remove All Filters',
    noResults: 'No results found',
    seeOverview: 'See Overview',
    close: 'Close',
    video: '{0} video',
  },
};

const DESKTOP = window.matchMedia('(min-width: 1024px)');
const TYPE_MAX_LENGTH = 40;

let instance = 0;

function getStrings() {
  const lang = (document.documentElement.lang || 'en').toLowerCase().split('-')[0];
  return { ...STRINGS.en, ...(STRINGS[lang] || {}) };
}

function format(template, value) {
  return template.replace('{0}', value);
}

function el(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

/* ---------- content parsing ---------- */

const HEADING = 'h1, h2, h3, h4, h5, h6';

function hasContent(cell) {
  return !!(cell.textContent.trim() || cell.querySelector('picture, img'));
}

/** a cell holding only one heading (a category row) */
function onlyHeading(cell) {
  const children = [...cell.children].filter((c) => c.textContent.trim() || c.querySelector('img'));
  return children.length === 1 && children[0].matches(HEADING) ? children[0] : null;
}

/** short plain text without links, media or headings: the product type cell */
function isTypeCell(cell) {
  const text = cell.textContent.trim();
  return !!text && text.length <= TYPE_MAX_LENGTH
    && !cell.querySelector(`a, picture, img, ul, ol, ${HEADING}`);
}

function toTypes(text) {
  return text.split(/,|\/|;/).map((t) => t.trim()).filter(Boolean);
}

/** an element holding only an image (e.g. <p><picture></p>) */
function isImageOnly(node) {
  return !!node.querySelector?.('picture, img') && !node.textContent.trim();
}

/* ---------- card ---------- */

/**
 * Classify the card cell: name (h3), tagline (italic paragraph), description,
 * CTA (primary button + trial note), then append the "See Overview" button.
 * @returns {{ card: Element, name: string }}
 */
function buildCard(cell, strings, hasOverview) {
  const card = el('div', 'cards-catalog-card-body');
  card.append(...cell.childNodes);

  const heading = card.querySelector(HEADING);
  if (heading) heading.classList.add('cards-catalog-name');
  const name = heading ? heading.textContent.trim() : '';

  const actions = el('div', 'cards-catalog-actions');
  let cta = null;
  [...card.querySelectorAll(':scope > p')].forEach((p) => {
    const text = p.textContent.trim();
    if (!text) {
      if (!p.querySelector('picture, img')) p.remove();
      return;
    }
    const button = p.querySelector('a.button');
    if (button && !cta) {
      cta = el('div', 'cards-catalog-trial');
      cta.append(button);
      p.remove();
      return;
    }
    const em = p.querySelector(':scope > em, :scope > i');
    if (!p.querySelector('a') && em && em.textContent.trim() === text) {
      p.classList.add('cards-catalog-tagline');
      return;
    }
    if (cta && cta.children.length === 1) {
      p.className = 'cards-catalog-trial-note';
      cta.append(p);
      return;
    }
    p.classList.add('cards-catalog-description');
  });

  if (cta) actions.append(cta);
  let overviewButton = null;
  if (hasOverview) {
    overviewButton = el('button', 'button secondary cards-catalog-overview-button', strings.seeOverview);
    overviewButton.type = 'button';
    overviewButton.setAttribute('aria-haspopup', 'dialog');
    actions.append(overviewButton);
  }
  if (actions.children.length) card.append(actions);
  return { card, name, overviewButton };
}

/* ---------- overview (modal content) ---------- */

/**
 * Split the overview cell into its parts. Nothing is attached to the document
 * until the modal opens, so no image or video loads with the page.
 * The first H1-H3 before any highlight is the modal title (often linked to the
 * product page); without it the modal shows the card name. Other headings
 * (H4 on the source) start the highlights.
 */
function parseOverview(cell) {
  const nodes = [...cell.children];
  const data = {
    icon: null, title: null, intro: [], cta: null, learnMore: null, media: null, highlights: [],
  };

  let current = null;
  nodes.forEach((node, i) => {
    if (!current && !data.title && node.matches('h1, h2, h3')) {
      data.title = node;
      return;
    }
    if (node.matches(HEADING)) {
      current = { title: node, body: [] };
      data.highlights.push(current);
      return;
    }
    if (current) {
      current.body.push(node);
      return;
    }
    if (i === 0 && isImageOnly(node)) {
      data.icon = node.querySelector('picture') || node.querySelector('img');
      return;
    }
    const wistia = [...node.querySelectorAll('a[href]')].find((a) => getWistiaId(a.href));
    if (wistia && !data.media && node.textContent.trim() === wistia.textContent.trim()) {
      data.media = { type: 'wistia', id: getWistiaId(wistia.href) };
      return;
    }
    if (isImageOnly(node) && !data.media) {
      data.media = { type: 'image', node: node.querySelector('picture') || node.querySelector('img') };
      return;
    }
    const button = node.querySelector('a.button');
    if (button) {
      if (button.classList.contains('secondary')) {
        if (!data.learnMore) data.learnMore = button;
      } else if (!data.cta) data.cta = button;
      return;
    }
    if (node.textContent.trim()) data.intro.push(node);
  });
  return data;
}

function lazyImages(root) {
  root.querySelectorAll('img').forEach((img) => {
    img.loading = 'lazy';
    img.decoding = 'async';
  });
}

/**
 * Fill the modal for one product. Videos get a poster (Wistia swatch) and the
 * Wistia iframe is created here, i.e. only once the modal is opened.
 */
function renderOverview(dialog, product, strings) {
  const { overview, name } = product;
  const titleId = `${dialog.id}-title`;
  const inner = dialog.querySelector('.cards-catalog-modal-inner');
  inner.replaceChildren();

  const header = el('div', 'cards-catalog-modal-header');
  const title = el('div', 'cards-catalog-modal-title');
  if (overview.icon) {
    const icon = el('div', 'cards-catalog-modal-icon');
    icon.append(overview.icon.cloneNode(true));
    title.append(icon);
  }
  // the overview title (linked to the product page on the source), else the card name
  const titleText = overview.title?.textContent.trim() || name;
  const heading = el('h2');
  const titleLink = overview.title?.querySelector('a[href]');
  if (titleLink) {
    const link = titleLink.cloneNode(true);
    link.className = 'cards-catalog-modal-title-link';
    heading.append(link);
  } else {
    heading.textContent = titleText;
  }
  heading.id = titleId;
  title.append(heading);
  header.append(title);
  if (overview.cta) {
    const cta = el('div', 'cards-catalog-modal-cta');
    cta.append(overview.cta.cloneNode(true));
    header.append(cta);
  }
  const close = el('button', 'cards-catalog-modal-close');
  close.type = 'button';
  close.setAttribute('aria-label', strings.close);

  const main = el('div', 'cards-catalog-modal-main');
  overview.intro.forEach((node) => main.append(node.cloneNode(true)));
  if (overview.learnMore) {
    const more = el('p', 'cards-catalog-modal-more');
    more.append(overview.learnMore.cloneNode(true));
    main.append(more);
  }
  if (overview.media?.type === 'wistia') {
    const { id } = overview.media;
    const video = el('div', 'cards-catalog-modal-video');
    const poster = el('img');
    poster.src = `https://fast.wistia.com/embed/medias/${id}/swatch`;
    poster.alt = '';
    poster.loading = 'lazy';
    const iframe = el('iframe');
    iframe.src = `https://fast.wistia.net/embed/iframe/${id}?seo=false&videoFoam=false`;
    iframe.title = format(strings.video, titleText);
    // `allow` grants fullscreen; adding allowfullscreen too only triggers a console warning
    iframe.allow = 'autoplay; fullscreen';
    iframe.addEventListener('load', () => video.classList.add('is-loaded'), { once: true });
    video.append(poster, iframe);
    main.append(video);
  } else if (overview.media?.type === 'image') {
    const media = el('div', 'cards-catalog-modal-image');
    media.append(overview.media.node.cloneNode(true));
    main.append(media);
  }

  const body = el('div', 'cards-catalog-modal-body');
  body.append(main);
  if (overview.highlights.length) {
    const aside = el('div', 'cards-catalog-modal-highlights');
    overview.highlights.forEach(({ title: t, body: b }) => {
      const item = el('div', 'cards-catalog-modal-highlight');
      const h = el('h3', '', t.textContent.trim());
      item.append(h, ...b.map((n) => n.cloneNode(true)));
      aside.append(item);
    });
    body.append(aside);
  }

  // the close button comes first (as on the source), so Tab moves from it to the
  // trial button; it is positioned at the top right by CSS
  inner.append(close, header, body);
  lazyImages(inner);
  dialog.setAttribute('aria-labelledby', titleId);
}

/* ---------- dialogs ---------- */

let lockCount = 0;
let savedOverflow = '';
function lockScroll(lock) {
  const root = document.documentElement;
  if (lock) {
    if (lockCount === 0) {
      savedOverflow = root.style.overflow;
      root.style.overflow = 'hidden';
    }
    lockCount += 1;
  } else {
    lockCount = Math.max(0, lockCount - 1);
    if (lockCount === 0) root.style.overflow = savedOverflow;
  }
}

/**
 * A native modal <dialog>: focus stays inside (the page is inert), Escape
 * closes it, and a click on the backdrop closes it. Focus returns to the
 * opener on close.
 */
function createDialog(className, id) {
  const dialog = el('dialog', className);
  dialog.id = id;
  // the inner wrapper fills the box, so a click on the dialog itself is on the backdrop
  dialog.addEventListener('click', (e) => {
    if (e.target === dialog) dialog.close();
  });
  dialog.addEventListener('close', () => {
    lockScroll(false);
    const { opener } = dialog;
    dialog.opener = null;
    dialog.dispatchEvent(new CustomEvent('cards-catalog:closed'));
    if (opener?.isConnected) opener.focus();
  });
  return dialog;
}

function openDialog(dialog, opener) {
  if (dialog.open) return;
  dialog.opener = opener;
  dialog.showModal();
  lockScroll(true);
}

/* ---------- filter ---------- */

function buildFacet(key, label, values, blockId) {
  const facet = el('div', 'cards-catalog-facet');
  facet.dataset.facet = key;
  const toggle = el('button', 'cards-catalog-facet-toggle', label);
  toggle.type = 'button';
  const listId = `${blockId}-${key}`;
  toggle.setAttribute('aria-expanded', 'false');
  toggle.setAttribute('aria-controls', listId);
  const list = el('ul', 'cards-catalog-facet-options');
  list.id = listId;
  list.hidden = true;
  list.setAttribute('aria-label', label);
  values.forEach((value) => {
    const li = el('li');
    const input = el('input');
    input.type = 'checkbox';
    input.value = value;
    input.dataset.facet = key;
    input.id = `${listId}-${toClassName(value)}`;
    const lbl = el('label', '', value);
    lbl.htmlFor = input.id;
    li.append(input, lbl);
    list.append(li);
  });
  toggle.addEventListener('click', () => {
    const expanded = toggle.getAttribute('aria-expanded') === 'true';
    toggle.setAttribute('aria-expanded', String(!expanded));
    list.hidden = expanded;
  });
  facet.append(toggle, list);
  return facet;
}

/**
 * Cards catalog: filterable product catalog. One block table: an optional
 * 1-cell note row (shown under the filter), 1-cell rows holding only an H2
 * (category; following products belong to it) and 3-cell product rows
 * (card | product type | overview). See README.md.
 * @param {Element} block
 */
export default function decorate(block) {
  instance += 1;
  const blockId = `cards-catalog-${instance}`;
  const strings = getStrings();

  /* parse rows */
  const noteNodes = [];
  const groups = [];
  let group = null;
  const products = [];

  [...block.children].forEach((row) => {
    const cells = [...row.children].filter(hasContent);
    if (!cells.length) return;

    const heading = cells.length === 1 ? onlyHeading(cells[0]) : null;
    if (heading) {
      group = { heading, name: heading.textContent.trim(), products: [] };
      groups.push(group);
      return;
    }

    // the card is the first cell (the overview cell has an H3 title too)
    const cardCell = cells[0].querySelector(HEADING) ? cells[0]
      : cells.find((c) => c.querySelector(HEADING)) || cells[0];
    if (cells.length === 1 && !cardCell.querySelector(HEADING)) {
      noteNodes.push(...cardCell.childNodes);
      return;
    }

    const rest = cells.filter((c) => c !== cardCell);
    const typeCell = rest.find(isTypeCell);
    const overviewCell = rest.find((c) => c !== typeCell);
    const overview = overviewCell ? parseOverview(overviewCell) : null;
    const { card, name, overviewButton } = buildCard(cardCell, strings, !!overview);

    if (!group) {
      group = { heading: null, name: '', products: [] };
      groups.push(group);
    }
    const product = {
      name,
      category: group.name,
      types: typeCell ? toTypes(typeCell.textContent) : [],
      overview,
      overviewButton,
      li: el('li', 'cards-catalog-card'),
    };
    product.li.append(card);
    group.products.push(product);
    products.push(product);
  });

  /* catalog: groups of cards */
  const catalog = el('div', 'cards-catalog-groups');
  groups.forEach((g) => {
    const section = el('div', 'cards-catalog-group');
    const head = el('div', 'cards-catalog-group-head');
    if (g.heading) {
      g.heading.classList.add('cards-catalog-group-title');
      head.append(g.heading);
    }
    g.count = el('p', 'cards-catalog-group-count');
    head.append(g.count);
    const list = el('ul', 'cards-catalog-list');
    g.products.forEach((p) => list.append(p.li));
    section.append(head, list);
    g.section = section;
    catalog.append(section);
  });

  /* filter panel */
  const compare = (a, b) => a.localeCompare(b, document.documentElement.lang || 'en');
  const categories = [...new Set(groups.map((g) => g.name).filter(Boolean))].sort(compare);
  const types = [...new Set(products.flatMap((p) => p.types))].sort(compare);

  const panel = el('div', 'cards-catalog-panel');
  const panelHead = el('div', 'cards-catalog-panel-head');
  const filterLabel = el('p', 'cards-catalog-filter-label', strings.filter);
  filterLabel.id = `${blockId}-filter-label`;
  const drawerClose = el('button', 'cards-catalog-drawer-close');
  drawerClose.type = 'button';
  drawerClose.setAttribute('aria-label', strings.closeFilter);
  panelHead.append(filterLabel, drawerClose);
  const facets = el('div', 'cards-catalog-facets');
  facets.setAttribute('role', 'group');
  facets.setAttribute('aria-labelledby', filterLabel.id);
  if (categories.length) facets.append(buildFacet('category', strings.category, categories, blockId));
  if (types.length) facets.append(buildFacet('type', strings.productType, types, blockId));
  const panelFoot = el('div', 'cards-catalog-panel-foot');
  const seeResults = el('button', 'button primary cards-catalog-see-results', strings.seeResults);
  seeResults.type = 'button';
  panelFoot.append(seeResults);
  panel.append(panelHead, facets, panelFoot);

  const sidebar = el('div', 'cards-catalog-sidebar');
  sidebar.append(panel);
  if (noteNodes.length) {
    const note = el('div', 'cards-catalog-note');
    note.append(...noteNodes);
    sidebar.append(note);
  }

  /* status line, chips, empty state */
  const toolbar = el('div', 'cards-catalog-toolbar');
  const openFilter = el('button', 'cards-catalog-filter-open', strings.openFilter);
  openFilter.type = 'button';
  openFilter.setAttribute('aria-haspopup', 'dialog');
  toolbar.append(openFilter);

  const status = el('div', 'cards-catalog-status');
  status.hidden = true;
  const showing = el('p', 'cards-catalog-showing');
  showing.setAttribute('role', 'status');
  const chipsRow = el('div', 'cards-catalog-chips-row');
  const chips = el('ul', 'cards-catalog-chips');
  const removeAll = el('button', 'cards-catalog-remove-all', strings.removeAll);
  removeAll.type = 'button';
  chipsRow.append(chips, removeAll);
  status.append(showing, chipsRow);

  const empty = el('p', 'cards-catalog-empty', strings.noResults);
  empty.hidden = true;

  const content = el('div', 'cards-catalog-content');
  content.append(toolbar, status, empty, catalog);

  const layout = el('div', 'cards-catalog-layout');
  if (!categories.length && !types.length) block.classList.add('cards-catalog-no-filter');
  layout.append(sidebar, content);

  /* dialogs */
  const drawer = createDialog('cards-catalog-drawer', `${blockId}-drawer`);
  drawer.setAttribute('aria-labelledby', filterLabel.id);
  const modal = createDialog('cards-catalog-modal', `${blockId}-modal`);
  modal.append(el('div', 'cards-catalog-modal-inner'));

  block.replaceChildren(layout, drawer, modal);

  /* filtering */
  const selected = []; // [{ facet, value }] in selection order

  function countText(n) {
    return format(n === 1 ? strings.product : strings.products, n);
  }

  /** keep focus in the filter UI when the focused chip / link disappears */
  function focusAfterRemove() {
    const target = chips.querySelector('button')
      || (DESKTOP.matches ? facets.querySelector('.cards-catalog-facet-toggle') : openFilter);
    target?.focus();
  }

  function apply() {
    const cats = selected.filter((s) => s.facet === 'category').map((s) => s.value);
    const tps = selected.filter((s) => s.facet === 'type').map((s) => s.value);
    let total = 0;
    groups.forEach((g) => {
      let visible = 0;
      g.products.forEach((p) => {
        const show = (!cats.length || cats.includes(p.category))
          && (!tps.length || p.types.some((t) => tps.includes(t)));
        p.li.hidden = !show;
        if (show) {
          // divider classes follow the visible order (2-column grid)
          p.li.classList.toggle('cards-catalog-card-start', visible % 2 === 0);
          visible += 1;
        }
      });
      const lastRow = visible % 2 === 0 ? 2 : 1;
      let index = 0;
      g.products.forEach((p) => {
        if (p.li.hidden) return;
        p.li.classList.toggle('cards-catalog-card-last', index === visible - 1);
        p.li.classList.toggle('cards-catalog-card-last-row', index >= visible - lastRow);
        index += 1;
      });
      g.count.textContent = countText(visible);
      g.section.hidden = visible === 0;
      total += visible;
    });

    const active = selected.length > 0;
    status.hidden = !active;
    // as on the source, "No results found" takes the place of the "Showing" line
    // above the chips; the separate message only covers a catalog without products
    empty.hidden = total > 0 || active;
    // "Showing <strong>N</strong> products"
    const text = format(strings.showing, countText(total));
    const at = text.indexOf(String(total));
    if (total === 0) showing.textContent = strings.noResults;
    else if (at < 0) showing.textContent = text;
    else {
      showing.replaceChildren(
        text.slice(0, at),
        el('strong', '', String(total)),
        text.slice(at + String(total).length),
      );
    }

    chips.replaceChildren(...selected.map(({ facet, value }) => {
      const li = el('li');
      const chip = el('button', 'cards-catalog-chip', value);
      chip.type = 'button';
      chip.setAttribute('aria-label', format(strings.removeFilter, value));
      chip.addEventListener('click', () => {
        const input = facets.querySelector(`input[data-facet="${facet}"][value="${CSS.escape(value)}"]`);
        if (input) input.checked = false;
        selected.splice(selected.findIndex((s) => s.facet === facet && s.value === value), 1);
        apply();
        focusAfterRemove();
      });
      li.append(chip);
      return li;
    }));
    block.classList.toggle('cards-catalog-filtered', active);
  }

  facets.addEventListener('change', (e) => {
    const input = e.target.closest('input[type="checkbox"]');
    if (!input) return;
    const { facet } = input.dataset;
    const { value } = input;
    const i = selected.findIndex((s) => s.facet === facet && s.value === value);
    if (input.checked && i < 0) selected.push({ facet, value });
    if (!input.checked && i >= 0) selected.splice(i, 1);
    apply();
  });

  removeAll.addEventListener('click', () => {
    selected.length = 0;
    facets.querySelectorAll('input:checked').forEach((input) => { input.checked = false; });
    apply();
    focusAfterRemove();
  });

  /* mobile drawer: the panel moves into the drawer while it is open */
  openFilter.addEventListener('click', () => {
    drawer.append(panel);
    openDialog(drawer, openFilter);
    drawerClose.focus();
  });
  drawerClose.addEventListener('click', () => drawer.close());
  seeResults.addEventListener('click', () => drawer.close());
  drawer.addEventListener('cards-catalog:closed', () => sidebar.prepend(panel));
  DESKTOP.addEventListener('change', () => {
    if (DESKTOP.matches && drawer.open) drawer.close();
  });

  /* overview modal */
  modal.addEventListener('click', (e) => {
    if (e.target.closest('.cards-catalog-modal-close')) modal.close();
  });
  modal.addEventListener('cards-catalog:closed', () => {
    // stop playback: drop the player
    modal.querySelector('.cards-catalog-modal-inner').replaceChildren();
  });
  products.forEach((product) => {
    if (!product.overviewButton) return;
    product.overviewButton.setAttribute('aria-controls', modal.id);
    product.overviewButton.addEventListener('click', () => {
      renderOverview(modal, product, strings);
      openDialog(modal, product.overviewButton);
      modal.querySelector('.cards-catalog-modal-close').focus();
    });
  });

  apply();
}
